plugins/netbox-cert-plugin/netbox_cert_plugin/urls.py
"""URL definitions"""

from django.urls import path
from netbox_cert_plugin import views, models
from netbox.views.generic import ObjectChangeLogView, ObjectJournalView


urlpatterns = (

    # Cert
    path('certificates/', views.CertificateListView.as_view(), name='certificate_list'),
    path('certificates/add/', views.CertificateEditView.as_view(), name='certificate_add'),
    path('certificates/import/', views.CertificateBulkImportView.as_view(), name='certificate_import'),
    path('certificates/delete/', views.CertificateBulkDeleteView.as_view(), name='certificate_bulk_delete'),
    path('certificates/<int:pk>/', views.CertificateView.as_view(), name='certificate'),
    path('certificates/<int:pk>/edit/', views.CertificateEditView.as_view(), name='certificate_edit'),
    path('certificates/<int:pk>/delete/', views.CertificateDeleteView.as_view(), name='certificate_delete'),
    path('certificates/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='certificate_changelog', kwargs={
        'model': models.Certificate
    }),
    path('certificates/<int:pk>/journal/', ObjectJournalView.as_view(), name='certificate_journal', kwargs={
        'model': models.Certificate
    }),
)

plugins/netbox-cert-plugin/netbox_cert_plugin/models.py
"""Models definitions"""

from django.db import models
from django.urls import reverse
from django.contrib.postgres.fields.array import ArrayField
from netbox.models import NetBoxModel
from utilities.choices import ChoiceSet


class CaChoices(ChoiceSet):
    """CA choices definition class"""

    key = "Certificate.ca"

    DEFAULT_VALUE = "letsencrypt"

    CHOICES = [
        ("letsencrypt", "Let's Encrypt", "yellow"),
        ("commissign", "CommisSign", "red"),
        ("globalsign", "GlobalSign", "blue"),
    ]


class ExpirationTimeChoices(ChoiceSet):
    """Expiration time choices definition class"""

    key = "Certificate.expiration_time"

    DEFAULT_VALUE = "1m"

    CHOICES = [
        ("1m", "1 month", "blue"),
        ("3m", "3 months", "blue"),
        ("6m", "6 months", "blue"),
        ("1y", "1 year", "blue"),
        ("3y", "3 year", "blue"),
    ]


class StateChoices(ChoiceSet):
    """CA choices definition class"""

    key = "Certificate.state"

    DEFAULT_VALUE = "to_be_created"

    CHOICES = [
        ("to_be_created", "To be created", "yellow"),
        ("creating", "Creating", "green"),
        ("errored", "Errored", "red"),
        ("valid", "Valid", "blue"),
        ("to_be_renewed", "To be renewed", "black"),
        ("renewing", "Renewing", "green"),
    ]


class Certificate(NetBoxModel):
    """Certificate definition class"""

    cn = models.CharField(
        max_length=256,
        blank=False,
        verbose_name="Common Name",
        unique=True,
        help_text="Unique Common Name",
    )
    alt_name = ArrayField(
        base_field=models.CharField(max_length=256),
        null=True,
        blank=True,
        verbose_name="Alt Name",
        help_text="Alt Name is a list of host separated by commas (e.g. alt1,alt2,alt3)",
    )
    ca = models.CharField(
        max_length=32,
        choices=CaChoices,
        default=CaChoices.DEFAULT_VALUE,
        blank=False,
        verbose_name="Certificate Authority",
    )
    expiration_time = models.CharField(
        max_length=2,
        choices=ExpirationTimeChoices,
        default=ExpirationTimeChoices.DEFAULT_VALUE,
        blank=False,
        verbose_name="Expiration time needed",
    )
    cert_created_at = models.DateField(
        blank=True, null=True, verbose_name="Effective certificate's creation date"
    )
    cert_expired_at = models.DateField(
        blank=True, null=True, verbose_name="Effective certificate's expiration date"
    )
    state = models.CharField(
        max_length=32,
        choices=StateChoices,
        default=StateChoices.DEFAULT_VALUE,
        blank=False,
        verbose_name="Certificate State",
    )

    class Meta:
        ordering = ["cn"]

    def __str__(self):
        return f"{self.cn}"

    def get_absolute_url(self):
        """override"""
        return reverse("plugins:netbox_cert_plugin:certificate", args=[self.pk])

plugins/netbox-cert-plugin/netbox_cert_plugin/templates/netbox_cert_plugin/certificate.html
{% extends 'generic/object.html' %}

{% block content %}
<div class="row mb-3">
  <div class="col col-md-6">
    <div class="card">
      <h5 class="card-header">CERTIFICATE</h5>
      <div class="card-body">
        <table class="table table-hover attr-table">
          <tr>
            <th scope="row">Common Name</th>
            <td>{{ object.cn }}</td>
          </tr>
          <tr>
            <th scope="row">Certificate Authority</th>
            <td>{{ object.get_ca_display }}</td>
          </tr>
          <tr>
            <th scope="row">Effective certificate's expiration date</th>
            <td>{{ object.cert_expired_at|placeholder }}</td>
          </tr>
        </table>
      </div>
    </div>
    {% include 'inc/panels/custom_fields.html' %}
    {% include 'inc/panels/tags.html' %}
  </div>
  <div class="col col-md-6">
    <div class="card">
      <h5 class="card-header">Details</h5>
      <div class="card-body">
        <table class="table table-hover attr-table">
          <tr>
            <th scope="row">Alt name</th>
            <td>{{ object.alt_name|placeholder }}</td>
          </tr>
          <tr>
            <th scope="row">Expiration time</th>
            <td>{{ object.get_expiration_time_display|placeholder }}</td>
          </tr>
          <tr>
            <th scope="row">State</th>
            <td>{{ object.get_state_display|placeholder }}</td>
          </tr>
          <tr>
            <th scope="row">Effective certificate's creation date</th>
            <td>{{ object.cert_created_at|placeholder }}</td>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock content %}