plugins/netbox-rps-plugin/netbox_rps_plugin/urls.py
"""URL definitions"""

from django.urls import path
from netbox_rps_plugin import views, models
from netbox.views.generic import ObjectChangeLogView, ObjectJournalView


urlpatterns = (

    # Mapping
    path('mappings/', views.MappingListView.as_view(), name='mapping_list'),
    path('mappings/add/', views.MappingEditView.as_view(), name='mapping_add'),
    path('mappings/import/', views.MappingBulkImportView.as_view(), name='mapping_import'),
    path('mappings/delete/', views.MappingBulkDeleteView.as_view(), name='mapping_bulk_delete'),
    path('mappings/<int:pk>/', views.MappingView.as_view(), name='mapping'),
    path('mappings/<int:pk>/edit/', views.MappingEditView.as_view(), name='mapping_edit'),
    path('mappings/<int:pk>/delete/', views.MappingDeleteView.as_view(), name='mapping_delete'),
    path('mappings/<int:pk>/http-headers/', views.MappingHttpHeadersView.as_view(), name='mapping_httpheader'),
    path('mappings/<int:pk>/saml-config/', views.MappingSamlConfigView.as_view(), name='mapping_samlconfig'),
    path('mappings/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='mapping_changelog', kwargs={
        'model': models.Mapping
    }),
    path('mappings/<int:pk>/journal/', ObjectJournalView.as_view(), name='mapping_journal', kwargs={
        'model': models.Mapping
    }),

    # HTTP Headers
    path('http-headers/', views.HttpHeaderListView.as_view(), name='httpheader_list'),
    path('http-headers/add/', views.HttpHeaderEditView.as_view(), name='httpheader_add'),
    path('http-headers/delete/', views.HttpHeaderBulkDeleteView.as_view(), name='httpheaders_bulk_delete'),
    path('http-headers/<int:pk>/', views.HttpHeaderView.as_view(), name='httpheader'),
    path('http-headers/<int:pk>/edit/', views.HttpHeaderEditView.as_view(), name='httpheader_edit'),
    path('http-headers/<int:pk>/delete/', views.HttpHeaderDeleteView.as_view(), name='httpheader_delete'),
    path('http-headers/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='httpheader_changelog', kwargs={
        'model': models.HttpHeader
    }),
    path('http-headers/<int:pk>/journal/', ObjectJournalView.as_view(), name='httpheader_journal', kwargs={
        'model': models.HttpHeader
    }),

    # Saml Config
    path('saml-configs/add/', views.SamlConfigEditView.as_view(), name='samlconfig_add'),
    path('saml-configs/<int:pk>/edit/', views.SamlConfigEditView.as_view(), name='samlconfig_edit'),
    path('saml-configs/<int:pk>/delete/', views.SamlConfigDeleteView.as_view(), name='samlconfig_delete'),
)

plugins/netbox-rps-plugin/netbox_rps_plugin/models.py
"""Models definitions"""

from typing import Any
from urllib.parse import urlparse
from django.core.exceptions import ValidationError
from django.conf import settings
from django.db import models
from django.db.models import Model
from django.urls import reverse
from django.core.validators import URLValidator, MaxValueValidator, MinValueValidator
from django.contrib.postgres.fields.array import ArrayField
from netbox.models import NetBoxModel
from utilities.choices import ChoiceSet

URL_MAX_SIZE = 2000
DEFAULT_SORRY_PAGE = settings.PLUGINS_CONFIG["netbox_rps_plugin"]["default_sorry_page"]


def clean_url(raw_url):
    """Clean an URL"""

    o = urlparse(raw_url)

    credential = ":".join(
        tuple(filter(lambda item: item is not None, (o.username, o.password)))
    )

    hostname = o.hostname if o.port is None else ":".join((o.hostname, str(o.port)))

    return (
        o._replace(netloc=hostname)
        if len(credential) == 0
        else o._replace(netloc="@".join((credential, hostname)))
    ).geturl()


class FilteredURLField(models.URLField):
    """URLField definition class"""

    def clean(self, value: Any, model_instance: Model | None) -> Any:
        """Clean Field value"""

        return clean_url(super().clean(value, model_instance))


class AuthenticationChoices(ChoiceSet):
    """Authentication choices definition class"""

    key = "Mapping.authentication"

    DEFAULT_VALUE = "none"

    CHOICES = [
        ("none", "None", "dark"),
        ("ldap", "Ldap", "blue"),
        ("ecas", "Ecas", "blue"),
    ]


class ApplyToChoices(ChoiceSet):
    """Apply to choices definition class"""

    key = "HttpHeader.applyTo"

    DEFAULT_VALUE = "request"

    CHOICES = [
        ("request", "Request", "blue"),
        ("response", "Response", "red"),
    ]


class ExtraProtocolChoices(ChoiceSet):
    """Protocol choices definition class"""

    key = "Mapping.protocol"

    WEBSOCKET_SECURE = "websocket"

    CHOICES = [
        (WEBSOCKET_SECURE, "Websocket", "blue"),
    ]


def default_protocol():
    """Return the default protocols"""
    return []


class Mapping(NetBoxModel):
    """Mapping definition class"""

    source = FilteredURLField(
        max_length=URL_MAX_SIZE,
        blank=False,
        verbose_name="Source",
        validators=[URLValidator(schemes=["http", "https"])],
        unique=True,
    )
    target = FilteredURLField(
        max_length=URL_MAX_SIZE,
        blank=False,
        verbose_name="Target",
        validators=[URLValidator(schemes=["http", "https"])],
    )
    authentication = models.CharField(
        max_length=30,
        choices=AuthenticationChoices,
        default=AuthenticationChoices.DEFAULT_VALUE,
        blank=False,
        verbose_name="Auth",
    )
    testingpage = models.URLField(
        max_length=URL_MAX_SIZE,
        blank=True,
        null=True,
        validators=[URLValidator(schemes=["http", "https"])],
    )
    webdav = models.BooleanField(
        default=False,
    )
    Comment = models.CharField(max_length=500, blank=True)
    gzip_proxied = models.BooleanField(default=False)
    keepalive_requests = models.IntegerField(
        default=1000, validators=[MinValueValidator(100), MaxValueValidator(5000)]
    )
    keepalive_timeout = models.IntegerField(
        default=75, validators=[MinValueValidator(1), MaxValueValidator(300)]
    )
    proxy_cache = models.BooleanField(default=False)
    proxy_read_timeout = models.IntegerField(
        default=60, validators=[MinValueValidator(1), MaxValueValidator(300)]
    )
    client_max_body_size = models.IntegerField(
        default=1, validators=[MinValueValidator(1), MaxValueValidator(255)]
    )
    sorry_page = models.URLField(
        max_length=URL_MAX_SIZE,
        blank=False,
        verbose_name="Sorry Page",
        validators=[URLValidator(schemes=["http", "https"])],
        default=DEFAULT_SORRY_PAGE,
    )
    extra_protocols = ArrayField(
        base_field=models.CharField(max_length=32, choices=ExtraProtocolChoices),
        null=False,
        blank=True,
        verbose_name="Extra Protocols",
        default=default_protocol,
    )

    class Meta:
        ordering = ("source", "target")
        constraints = [
            models.CheckConstraint(
                check=~models.Q(source__exact=models.F("target")),
                name="%(app_label)s_%(class)s_check_target_source_url",
            )
        ]

    def __str__(self):
        return f"{self.source}"

    def get_absolute_url(self):
        """override"""
        return reverse("plugins:netbox_rps_plugin:mapping", args=[self.pk])

    def clean(self):
        """Clean model method for validation"""
        super().clean()

        if self.source == self.target:
            raise ValidationError(
                {"target": "Target URL cannot be equal to source URL."}
            )


class SamlConfig(NetBoxModel):
    """SAML config definition class"""

    acs_url = models.CharField(
        max_length=URL_MAX_SIZE,
        blank=False,
        verbose_name="ACS URL",
        validators=[URLValidator(message="It must be a url")],
    )
    logout_url = models.CharField(
        max_length=URL_MAX_SIZE,
        blank=False,
        verbose_name="Logout URL",
        validators=[URLValidator(message="It must be a url")],
    )
    force_nauth = models.BooleanField(
        default=False,
    )
    Mapping = models.OneToOneField(
        Mapping,
        on_delete=models.CASCADE,
        related_name="saml_config",
        db_column="mapping_id",
        name="mapping",
    )


class HttpHeader(NetBoxModel):
    """HTTP Header definition class"""

    mapping = models.ForeignKey(
        Mapping, on_delete=models.CASCADE, related_name="http_headers"
    )
    name = models.CharField(max_length=120, blank=False, verbose_name="Header name")
    value = models.CharField(
        max_length=256, null=True, blank=True, verbose_name="Header value"
    )
    apply_to = models.CharField(
        max_length=30,
        choices=ApplyToChoices,
        default=ApplyToChoices.DEFAULT_VALUE,
        blank=False,
        verbose_name="Apply to",
    )

    class Meta:
        unique_together = ["mapping", "name", "apply_to"]
        ordering = ["name"]

    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        """override"""
        return reverse("plugins:netbox_rps_plugin:httpheader", args=[self.pk])

plugins/netbox-rps-plugin/netbox_rps_plugin/templates/netbox_rps_plugin/httpheader.html
{% extends 'generic/object.html' %}

{% block content %}
  <div class="row mb-3">
    <div class="col col-md-6">
      <div class="card">
        <h5 class="card-header">HEADERS</h5>
        <div class="card-body">
          <table class="table table-hover attr-table">
            <tr>
              <th scope="row">Name</th>
              <td>{{ object.name }}</td>
            </tr>
            <tr>
              <th scope="row">Value</th>
              <td>{{ object.value }}</td>
            </tr>
            <tr>
                <th scope="row">Apply To</th>
                <td>{{ object.apply_to }}</td>
              </tr>
          </table>
        </div>
      </div>
      {% include 'inc/panels/custom_fields.html' %}
      {% include 'inc/panels/tags.html' %}
    </div>
  </div>
{% endblock content %}

plugins/netbox-rps-plugin/netbox_rps_plugin/templates/netbox_rps_plugin/mapping.html
{% extends 'generic/object.html' %}

{% block extra_controls %}
<a href="{% url 'plugins:netbox_rps_plugin:httpheader_add' %}?mapping={{ object.pk }}&return_url={{ object.get_absolute_url }}"
  class="btn btn-sm btn-primary">
  <span class="mdi mdi-plus-thick" aria-hidden="true"></span> Add HTTP Header
</a>
{% if not object.saml_config %}
<a href="{% url 'plugins:netbox_rps_plugin:samlconfig_add' %}?mapping={{ object.pk }}&return_url={{ object.get_absolute_url }}"
  class="btn btn-sm btn-primary">
  <span class="mdi mdi-plus-thick" aria-hidden="true"></span> Add <abbr
    title="Security Assertion Markup Language">SAML</abbr> Configuration
</a>
{% endif %}
{% endblock %}

{% block content %}
<div class="row mb-3">
  <div class="col col-md-6">
    <div class="card">
      <h5 class="card-header">MAPPINGS</h5>
      <div class="card-body">
        <table class="table table-hover attr-table">
          <tr>
            <th scope="row">Name</th>
            <td>{{ object.source }}</td>
          </tr>
          <tr>
            <th scope="row">Comment</th>
            <td>
              {% if object.Comment %}
              {{ object.Comment }}
              {% else %}
              {{ ''|placeholder }}
              {% endif %}
            </td>
          </tr>
        </table>
      </div>
    </div>
    {% include 'inc/panels/custom_fields.html' %}
    {% include 'inc/panels/tags.html' %}
  </div>
  <div class="col col-md-6">
    <div class="card">
      <h5 class="card-header">Details</h5>
      <div class="card-body">
        <table class="table table-hover attr-table">
          <tr>
            <th scope="row">Source</th>
            <td>{{ object.source }}</td>
          </tr>
          <tr>
            <th scope="row">Target</th>
            <td>{{ object.target }}</td>
          </tr>
          <tr>
            <th scope="row">Authentication</th>
            <td>{{ object.get_authentication_display|placeholder }}</td>
          </tr>
          <tr>
            <th scope="row">Testing page</th>
            <td>{{ object.testingpage }}</td>
          </tr>
          <tr>
            <th scope="row">Webdav</th>
            <td>{{ object.webdav|yesno }}</td>
          </tr>
          <tr>
            <th scope="row">Extra Protocols</th>
            <td>{{ object.extra_protocols|placeholder }}</td>
          </tr>
          <tr>
            <th scope="row">Comment</th>
            <td>
              {% if object.Comment %}
              {{ object.Comment }}
              {% else %}
              {{ ''|placeholder }}
              {% endif %}
            </td>
          </tr>
          <tr>
            <th scope="row">gzip proxied</th>
            <td>{{ object.gzip_proxied|yesno }}</td>
          </tr>
          <tr>
            <th scope="row">Keepalive requests</th>
            <td>{{ object.keepalive_requests }}</td>
          </tr>
          <tr>
            <th scope="row">Keepalive timeout</th>
            <td>{{ object.keepalive_timeout }}&nbsp;s</td>
          </tr>
          <tr>
            <th scope="row">Proxy cache</th>
            <td>{{ object.proxy_cache|yesno }}</td>
          </tr>
          <tr>
            <th scope="row">Proxy read timeout</th>
            <td>{{ object.proxy_read_timeout }}&nbsp;s</td>
          </tr>
          <tr>
            <th scope="row">Client max body size</th>
            <td>{{ object.client_max_body_size }}&nbsp;MB</td>
          </tr>
          <tr>
            <th scope="row">Sorry Page</th>
            <td>{{ object.sorry_page }}</td>
          </tr>
        </table>
      </div>
    </div>
    {% if object.saml_config %}
    <div class="card">
      <h5 class="card-header">SAML Configuration</h5>
      <div class="card-body">
        <table class="table table-hover attr-table">
          <tr>
            <th scope="row">ACS URL</th>
            <td>{{ object.saml_config.acs_url }}</td>
          </tr>
          <tr>
            <th scope="row">Logout URL</th>
            <td>{{ object.saml_config.logout_url }}</td>
          </tr>
          <tr>
            <th scope="row">Force AuthnRequest</th>
            <td>{{ object.saml_config.force_nauth }}</td>
          </tr>
        </table>
      </div>
    </div>
    {% endif %}
  </div>
</div>
{% endblock content %}

plugins/netbox-rps-plugin/netbox_rps_plugin/templates/netbox_rps_plugin/saml_config.html
{% extends 'generic/object.html' %}
{% load buttons %}
{% load perms %}

{% block content %}
<div class="row mb-3">
  <div class="col col-md-6">
    <div class="card">
      <h5 class="card-header">SAML Configuration</h5>
      <div class="card-body">
        <table class="table table-hover attr-table">
          <tr>
            <th scope="row">ACS URL</th>
            <td>{{ object.saml_config.acs_url }}</td>
          </tr>
          <tr>
            <th scope="row">Logout URL</th>
            <td>{{ object.saml_config.logout_url }}</td>
          </tr>
          <tr>
            <th scope="row">Force AuthnRequest</th>
            <td>{{ object.saml_config.force_nauth }}</td>
          </tr>
        </table>
      </div>
    </div>
    {% include 'inc/panels/custom_fields.html' %}
    {% include 'inc/panels/tags.html' %}
  </div>
</div>
<div class="controls">
  <div class="control-group">
    {% if request.user|can_change:object.saml_config %}
      {% edit_button object.saml_config %}
    {% endif %}
    {% if request.user|can_delete:object.saml_config %}
      {% delete_button object.saml_config %}
    {% endif %}
  </div>
</div>
{% endblock content %}